table 'Dim Promotion'
	lineageTag: 15bae9f4-16b0-4263-a9cb-e60aae66cf31

	measure 'Sum Dim' = SUM('Fact Table'[Net Sales ])
		lineageTag: bffb398b-18d4-475e-9591-9eb0b4e9ddd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PromotionID
		dataType: string
		lineageTag: c982f3c3-7c33-4eb6-b630-630f053b994e
		summarizeBy: none
		sourceColumn: PromotionID

		annotation SummarizationSetBy = Automatic

	column 'Promotion Name'
		dataType: string
		lineageTag: 1552d5f4-6cf1-453b-94c9-63893c3e4cbc
		summarizeBy: none
		sourceColumn: Promotion Name

		annotation SummarizationSetBy = Automatic

	column 'Ad Type'
		dataType: string
		lineageTag: ed8978c5-7a09-461b-8e34-0577899dc92c
		summarizeBy: none
		sourceColumn: Ad Type

		annotation SummarizationSetBy = Automatic

	column 'Coupon Code'
		dataType: string
		lineageTag: 38838374-70b1-4892-843b-dacd8a65ddce
		summarizeBy: none
		sourceColumn: Coupon Code

		annotation SummarizationSetBy = Automatic

	column 'Price Reduction Type'
		dataType: string
		lineageTag: 64422763-7b21-484a-8bf8-92e1fbd813ee
		summarizeBy: none
		sourceColumn: Price Reduction Type

		annotation SummarizationSetBy = Automatic

	column Percentage
		dataType: int64
		formatString: 0
		lineageTag: 74888d32-1091-4f4e-9f2f-0d3fd7941d26
		summarizeBy: none
		sourceColumn: Percentage

		annotation SummarizationSetBy = Automatic

	partition 'Dim Promotion' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\alefi\Downloads\DataAnanlystBootcamp-KNaik PowerBI\Proj1 - Sales Data Analysis\Store+Data.xlsx"), null, true),
				    #"Dim Promotion _Sheet" = Source{[Item="Dim Promotion ",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Dim Promotion _Sheet",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"PromotionID", type text}, {"Promotion Name", type text}, {"Ad Type", type text}, {"Coupon Code", type text}, {"Price Reduction Type", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "Percentage", each if [PromotionID] = "PR001" then 20 else if [PromotionID] = "PR002" then 10 else if [PromotionID] = "PR003" then 50 else if [PromotionID] = "PR004" then 50 else 70),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Percentage", Int64.Type}})
				in
				    #"Changed Type2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

