table 'Measures Table'
	lineageTag: 98bf9326-67d2-4df5-9348-e025223ab5d5

	measure 'Sum of Net Sales' = CALCULATE(SUM('Fact Table'[Net Sales ]),ALL('Date Table 1'),USERELATIONSHIP('Date Table 2'[Date],'Fact Table'[Date (dd/mm/yyyy)]))
		lineageTag: af3e7c3d-d796-4fa5-a4a8-fc4240eed3ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = CALCULATE(SUM('Fact Table'[Profit]),ALL('Date Table 1'),USERELATIONSHIP('Date Table 2'[Date],'Fact Table'[Date (dd/mm/yyyy)]))
		lineageTag: 8d016107-fe46-42c3-a28e-992023c4de17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity' = CALCULATE(SUM('Fact Table'[Units Sold]),ALL('Date Table 1'),USERELATIONSHIP('Date Table 2'[Date],'Fact Table'[Date (dd/mm/yyyy)]))
		formatString: 0
		lineageTag: 30566ff7-13b7-4d90-a2ae-2cdcfc75f4f1

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

